// Code generated by "stringer -type=itemType -output=gen_itemType.go"; DO NOT EDIT.

package main

import "strconv"

const _itemType_name = "itemErroritemEOFitemTextitemCodeFenceitemCodeitemTmplBlockStartitemJsonBlockStartitemBlockEnditemCommEnditemArgitemQuoteArg"

var _itemType_index = [...]uint8{0, 9, 16, 24, 37, 45, 63, 81, 93, 104, 111, 123}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
