// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

type PanelElem struct {
	react.Element
}

func buildPanel(cd react.ComponentDef) react.Component {
	return PanelDef{ComponentDef: cd}
}

func buildPanelElem(props PanelProps, children ...react.Element) *PanelElem {
	return &PanelElem{
		Element: react.CreateElement(buildPanel, props, children...),
	}
}

func (p PanelDef) RendersElement() react.Element {
	return p.Render()
}

// IsProps is an auto-generated definition so that PanelProps implements
// the myitcv.io/react.Props interface.
func (p PanelProps) IsProps() {}

// Props is an auto-generated proxy to the current props of Panel
func (p PanelDef) Props() PanelProps {
	uprops := p.ComponentDef.Props()
	return uprops.(PanelProps)
}

func (p PanelProps) EqualsIntf(val react.Props) bool {
	return p == val.(PanelProps)
}

var _ react.Props = PanelProps{}
