package main

type Gopher struct {
	Parts []string
}

type UpdateGopher interface {
	ResetGopher()
	UpdateGopher(part int, val string)
	RandomGopher()
}

type Config struct {
	Categories []*Category
}

type Category struct {
	Name    string
	Options []string
}

var hackConfig = &Config{
	Categories: []*Category{
		&Category{
			Name: "Body",
			Options: []string{
				"010-Body/blue_gopher",
				"010-Body/blue_spike_hair",
				"010-Body/brown_gopher",
				"010-Body/green_gopher",
				"010-Body/pink_gopher",
				"010-Body/purple_gopher",
			},
		},
		&Category{
			Name: "Eyes",
			Options: []string{
				"020-Eyes/crazy_eyes",
				"020-Eyes/eyelashes",
				"020-Eyes/eyes",
				"020-Eyes/eyes_angry",
				"020-Eyes/goofy_eyes",
				"020-Eyes/looking_left",
				"020-Eyes/looking_right",
				"020-Eyes/looking_up_lashes",
				"020-Eyes/looking_up_no_lashes",
			},
		},
		&Category{
			Name: "Shirts",
			Options: []string{
				"",
				"021-Shirts/1_up_shirt",
				"021-Shirts/Octocat",
				"021-Shirts/Octocat_1",
				"021-Shirts/Pivotal",
				"021-Shirts/black_heart_shirt",
				"021-Shirts/black_shirt",
				"021-Shirts/docker_shirt",
				"021-Shirts/emc_code",
				"021-Shirts/emc_code_shirt",
				"021-Shirts/freebsd_beastie",
				"021-Shirts/freebsd_shirt",
				"021-Shirts/game_over_shirt",
				"021-Shirts/gay_pride_shirt",
				"021-Shirts/girls_who_code_shirt",
				"021-Shirts/github",
				"021-Shirts/go_academy_shirt",
				"021-Shirts/gobuffalo_shirt",
				"021-Shirts/golang_news",
				"021-Shirts/golang_shirt",
				"021-Shirts/google_shirt",
				"021-Shirts/gopher_BBQ",
				"021-Shirts/gopher_starwars_shirt",
				"021-Shirts/gophercon_shirt",
				"021-Shirts/gotham_go_shirt",
				"021-Shirts/gotime",
				"021-Shirts/grey_shirt",
				"021-Shirts/groove_shirt",
				"021-Shirts/hawaiian_shirt",
				"021-Shirts/hawaiian_shirt_solid",
				"021-Shirts/heman_shirt",
				"021-Shirts/influx_db",
				"021-Shirts/kubernetes_shirt",
				"021-Shirts/linux_shirt",
				"021-Shirts/my_little_pony_shirt",
				"021-Shirts/new_relic_nerd_life",
				"021-Shirts/objectrocket_shirt",
				"021-Shirts/pacman_shirt",
				"021-Shirts/pacman_shirt_1",
				"021-Shirts/php_shirt",
				"021-Shirts/pink_rainbow_shirt",
				"021-Shirts/pink_shirt",
				"021-Shirts/rainbow_brite",
				"021-Shirts/shera_shirt",
				"021-Shirts/skull_and_crossbones",
				"021-Shirts/star_shirt",
				"021-Shirts/tetris",
				"021-Shirts/the_channellog",
				"021-Shirts/tuxedo",
				"021-Shirts/ubuntu",
				"021-Shirts/women_who_go",
				"021-Shirts/women_who_go_berlin",
				"021-Shirts/write_the_docs",
				"021-Shirts/zelda",
			},
		},
		&Category{
			Name: "Hair",
			Options: []string{
				"",
				"022-Hair/ash_blonde_hair",
				"022-Hair/black_hair",
				"022-Hair/blonde_bangs",
				"022-Hair/blonde_hair_blue_ears",
				"022-Hair/blonde_hair_pink_ears",
				"022-Hair/blonde_swoop_hair",
				"022-Hair/blue_ear_afro",
				"022-Hair/blue_ear_curly_hair",
				"022-Hair/brian_ketelsen_hair",
				"022-Hair/brown_hair_bangs",
				"022-Hair/brown_hair_blue_ears",
				"022-Hair/brown_hair_ears_blue",
				"022-Hair/brown_hair_long",
				"022-Hair/brown_hair_pink_ears",
				"022-Hair/brown_hawk",
				"022-Hair/brown_mohawk",
				"022-Hair/brown_swoop_hair",
				"022-Hair/center_brown_hair",
				"022-Hair/combed_front_brown_hair",
				"022-Hair/combed_front_grey_hair",
				"022-Hair/combed_left_red_hair",
				"022-Hair/combed_side_hair",
				"022-Hair/curly_blonde",
				"022-Hair/curly_red",
				"022-Hair/guy_short_black_hair",
				"022-Hair/hair_black",
				"022-Hair/hair_blonde",
				"022-Hair/hair_brown",
				"022-Hair/hair_red",
				"022-Hair/hipster_hair",
				"022-Hair/hipster_pack",
				"022-Hair/lavender_bangs",
				"022-Hair/long_blonde_hair",
				"022-Hair/long_dark_brown_hair",
				"022-Hair/man_bun",
				"022-Hair/pink_bangs",
				"022-Hair/pink_ear_afro",
				"022-Hair/pink_ear_curly_hair",
				"022-Hair/pink_hair_blue_ears",
				"022-Hair/pink_hair_pink_ears",
				"022-Hair/pink_unicorn",
				"022-Hair/rainbow_hair",
				"022-Hair/rainbow_unicorn",
				"022-Hair/rakyll_hair",
				"022-Hair/red_bangs",
				"022-Hair/red_hair_blue_ears",
				"022-Hair/red_hair_pink_ears",
				"022-Hair/red_hipster_hair",
				"022-Hair/red_mohawk",
				"022-Hair/red_swoop_hair",
				"022-Hair/side_hair",
				"022-Hair/the_dave_cheney_beard",
				"022-Hair/trump_hair",
			},
		},
		&Category{
			Name: "Facial Hair",
			Options: []string{
				"",
				"023-Facial_Hair/black_beard",
				"023-Facial_Hair/black_moustache",
				"023-Facial_Hair/black_stache",
				"023-Facial_Hair/blonde_beard",
				"023-Facial_Hair/blonde_moustache",
				"023-Facial_Hair/blonde_stache",
				"023-Facial_Hair/brown_beard",
				"023-Facial_Hair/brown_beard_1",
				"023-Facial_Hair/brown_beard_medium",
				"023-Facial_Hair/brown_moustache",
				"023-Facial_Hair/brown_pirate_beard",
				"023-Facial_Hair/brown_stache",
				"023-Facial_Hair/detailed_blonde_beard",
				"023-Facial_Hair/extra_long_brown_beard",
				"023-Facial_Hair/full_ash_blonde_beard",
				"023-Facial_Hair/full_blonde_beard",
				"023-Facial_Hair/full_red_beard",
				"023-Facial_Hair/full_redish_beard",
				"023-Facial_Hair/grey_stache",
				"023-Facial_Hair/mat_ryer_pirate_beard",
				"023-Facial_Hair/moustache_red",
				"023-Facial_Hair/multi_colored_beard",
				"023-Facial_Hair/red_beard",
				"023-Facial_Hair/red_soul_patch",
				"023-Facial_Hair/short_black_beard",
				"023-Facial_Hair/short_black_beard1",
				"023-Facial_Hair/short_blonde_beard",
				"023-Facial_Hair/short_copper_beard",
				"023-Facial_Hair/short_full_black_beard",
				"023-Facial_Hair/short_full_blonde_beard",
				"023-Facial_Hair/short_full_grey_beard",
				"023-Facial_Hair/short_full_red_beard",
				"023-Facial_Hair/small_brown_stache",
				"023-Facial_Hair/straight_stache",
				"023-Facial_Hair/stubble",
				"023-Facial_Hair/this_weird_thing",
			},
		},
		&Category{
			Name: "Glasses",
			Options: []string{
				"",
				"024-Glasses/all_black_sunglasses",
				"024-Glasses/black_rimmed_glasses",
				"024-Glasses/blue_lenses",
				"024-Glasses/blue_sunglasses",
				"024-Glasses/funky_glasses",
				"024-Glasses/funky_green_glasses",
				"024-Glasses/green_lenses",
				"024-Glasses/heart_glasses",
				"024-Glasses/hipster_glasses1",
				"024-Glasses/movie_glasses",
				"024-Glasses/nerd_glasses",
				"024-Glasses/pink_lenses",
				"024-Glasses/red_glasses",
				"024-Glasses/red_sunglasses",
				"024-Glasses/round_black_rimmed_glasses",
				"024-Glasses/round_glasses",
				"024-Glasses/round_red_sunglasses",
				"024-Glasses/small_black_sunglasses",
				"024-Glasses/square_glasses",
				"024-Glasses/square_glasses1",
				"024-Glasses/sunglasses",
			},
		},
		&Category{
			Name: "Hats and Hair Accessories",
			Options: []string{
				"",
				"025-Hats_and_Hair_Accessories/Large_black_yellow_bow",
				"025-Hats_and_Hair_Accessories/bandana",
				"025-Hats_and_Hair_Accessories/bat_gopher",
				"025-Hats_and_Hair_Accessories/beanie",
				"025-Hats_and_Hair_Accessories/birthday_hat",
				"025-Hats_and_Hair_Accessories/bunny_ears",
				"025-Hats_and_Hair_Accessories/cat_ears",
				"025-Hats_and_Hair_Accessories/flower_headband",
				"025-Hats_and_Hair_Accessories/gobuffalo_costume",
				"025-Hats_and_Hair_Accessories/graduation",
				"025-Hats_and_Hair_Accessories/headband",
				"025-Hats_and_Hair_Accessories/king_queen",
				"025-Hats_and_Hair_Accessories/moar_viking",
				"025-Hats_and_Hair_Accessories/pink_flower_headband",
				"025-Hats_and_Hair_Accessories/pirate_hat",
				"025-Hats_and_Hair_Accessories/ponzu_cms_costume",
				"025-Hats_and_Hair_Accessories/purple_bow",
				"025-Hats_and_Hair_Accessories/purple_flower",
				"025-Hats_and_Hair_Accessories/ship_captain",
				"025-Hats_and_Hair_Accessories/skull_bandana",
				"025-Hats_and_Hair_Accessories/stay_puft",
				"025-Hats_and_Hair_Accessories/steampunk_tophat",
				"025-Hats_and_Hair_Accessories/the_bill_kennedy",
				"025-Hats_and_Hair_Accessories/unicorn_horn_pink",
				"025-Hats_and_Hair_Accessories/viking_hat",
				"025-Hats_and_Hair_Accessories/wicked_tophat",
				"025-Hats_and_Hair_Accessories/yarmulke",
				"025-Hats_and_Hair_Accessories/yellow_bow",
			},
		},
		&Category{
			Name: "Extras",
			Options: []string{
				"",
				"027-Extras/Large_black_yellow_bow",
				"027-Extras/bowtie",
				"027-Extras/camera",
				"027-Extras/captain_america",
				"027-Extras/cellphone",
				"027-Extras/coffee",
				"027-Extras/gamer",
				"027-Extras/heart_lolli",
				"027-Extras/laptop",
				"027-Extras/lightsaber",
				"027-Extras/magic_wand",
				"027-Extras/moustache_pipe",
				"027-Extras/necklace",
				"027-Extras/popcorn",
				"027-Extras/red_polkadot_bow",
				"027-Extras/soda",
				"027-Extras/steampunk_glasses",
				"027-Extras/stripe_bowtie",
				"027-Extras/to_go_coffee",
				"027-Extras/unicorn_horn_pink",
				"027-Extras/valentines",
				"027-Extras/watch",
				"027-Extras/yellow_polkadot_bow",
			},
		},
	},
}
